# Generated by Django 5.1.1 on 2024-10-07 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_productentry_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productentry',
            old_name='product_name',
            new_name='product',
        ),
    ]
